package com.patodesapatos.dungeons.controller;

public enum MessageType {
    PING,
    CREATE_DUNGEON,
    JOIN_DUNGEON,
    WAITING,
    DUNGEON_STATE,
    UPDATE_ENTITY,
    SEND_CHAT_MESSAGE,
    SET_PLAYER_READY,
    CHANGE_DUNGEON_PRIVACY,
    LEAVE_DUNGEON,
    GET_WAITING_STATE,
    CHANGE_LEVEL,

    TILE_ENTITY,
    GET_TILE_ENTITY,
    ADD_TILE_ENTITY,

    INVENTORY,
    UPDATE_INVENTORY,
    GET_INVENTORY,

    BATTLE_START,
    BATTLE_STATE,
    JOIN_BATTLE,
    TURN_ACTION,
    UNIT_READY,
    BATTLE_END
}